// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartyId } from "../shared/PartyId";

export type ProducerInfo = { producerId: PartyId, catalogNb: string, };
