// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The format of the physical or digital medium used for distribution.
 */
export type ReleaseFormat = "Cd" | "DoubleCd" | "Vynil7" | "Vinyl10" | "Cassette" | "AudioDvd";
