// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The packaging type used for the physical release.
 */
export type ReleasePackaging = "JewelCase" | "SlimJewelCase" | "SuperJewelCase" | "Digipak" | "CardboardSleeve" | "Gatefold" | "PaperSleeve" | "KeepCase" | "SteelBook" | "AmarayCase" | "SnapCase" | "Longbox" | "Box" | "Clamshell" | "Tin" | "BlisterPack" | "Other";
