// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The general type of release based on track count or intent.
 */
export type ReleaseType = "Lp" | "DoubleLp" | "Ep" | "Single" | "Mixtape";
