// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The official status of the release in its publication lifecycle.
 */
export type ReleaseStatus = "Official" | "Promotional" | "ReRelease" | "SpecialEdition" | "Remastered" | "Bootleg" | "PseudoRelease" | "Withdrawn" | "Expunged" | "Cancelled";
