// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Country } from "../shared/Country";
import type { Date } from "../shared/Date";
import type { PartyId } from "../shared/PartyId";
import type { ProducerInfo } from "./ProducerInfo";
import type { ReleaseFormat } from "./ReleaseFormat";
import type { ReleasePackaging } from "./ReleasePackaging";
import type { ReleaseStatus } from "./ReleaseStatus";
import type { ReleaseType } from "./ReleaseType";

/**
 * Represents a commercial music release.
 *
 * This structure contains all metadata related to the distribution and packaging
 * of musical content, including track listings, production details, and commercial information.
 *
 * # Examples
 *
 * ## Album Release
 *
 * ```rust
 * use allfeat_midds_v2::{
 *     release::{Release, ReleaseType, ReleaseFormat, ReleasePackaging, ReleaseStatus},
 *     shared::PartyId,
 *     shared::{Date, Country},
 * };
 *
 * let album = Release {
 *     ean_upc: b"1234567890123".to_vec().try_into().unwrap(),
 *     creator: PartyId::Ipi(12345),
 *     producers: vec![].try_into().unwrap(),
 *     recordings: vec![].try_into().unwrap(),
 *     distributor_name: b"Music Distributor Inc".to_vec().try_into().unwrap(),
 *     manufacturer_name: b"Vinyl Press Co".to_vec().try_into().unwrap(),
 *     cover_contributors: vec![].try_into().unwrap(),
 *     title: b"My Album".to_vec().try_into().unwrap(),
 *     title_aliases: vec![].try_into().unwrap(),
 *     release_type: ReleaseType::Lp,
 *     format: ReleaseFormat::Cd,
 *     packaging: ReleasePackaging::JewelCase,
 *     date: Date { year: 2024, month: 6, day: 15 },
 *     country: Country::US,
 *     status: ReleaseStatus::Official,
 * };
 * ```
 *
 * ## Single Release
 *
 * ```rust
 * use allfeat_midds_v2::{
 *     release::{Release, ReleaseType, ReleaseFormat, ReleasePackaging, ReleaseStatus},
 *     shared::PartyId,
 *     shared::{Date, Country},
 * };
 *
 * let single = Release {
 *     ean_upc: b"9876543210987".to_vec().try_into().unwrap(),
 *     creator: PartyId::Ipi(67890),
 *     producers: vec![PartyId::Ipi(111111111)].try_into().unwrap(),
 *     recordings: vec![222222222].try_into().unwrap(),
 *     distributor_name: b"Digital Distributor".to_vec().try_into().unwrap(),
 *     manufacturer_name: b"Digital".to_vec().try_into().unwrap(),
 *     cover_contributors: vec![b"Cover Artist".to_vec().try_into().unwrap()].try_into().unwrap(),
 *     title: b"Hit Single".to_vec().try_into().unwrap(),
 *     title_aliases: vec![].try_into().unwrap(),
 *     release_type: ReleaseType::Single,
 *     format: ReleaseFormat::Cd,
 *     packaging: ReleasePackaging::Digipack,
 *     date: Date { year: 2024, month: 3, day: 1 },
 *     country: Country::GB,
 *     status: ReleaseStatus::Official,
 * };
 * ```
 */
export type Release = { 
/**
 * EAN or UPC code identifying the release (physical or digital).
 */
eanUpc: string, 
/**
 * The main creator IDs associated with this release.
 */
creator: PartyId, 
/**
 * List of producer MIDDS IDs who contributed to this release.
 */
producers: Array<ProducerInfo>, 
/**
 * List of track MIDDS IDs that are part of this release.
 */
recordings: Array<bigint>, 
/**
 * Name of the distributor responsible for the release.
 */
distributorName: string, 
/**
 * Name of the manufacturer responsible for physical production.
 */
manufacturerName: string, 
/**
 * Contributors to the release cover (designers, photographers, etc.).
 */
coverContributors: Array<string>, 
/**
 * Official title of the release.
 */
title: string, 
/**
 * Alternative titles (e.g. translations, acronyms, stylistic variations).
 */
titleAliases: Array<string>, 
/**
 * Type of the release (e.g. LP, EP, Single, Mixtape).
 */
releaseType: ReleaseType, 
/**
 * Format of the release medium (e.g. CD, Vinyl, Cassette).
 */
format: ReleaseFormat, 
/**
 * Packaging used for the physical release (e.g. Digipack, Jewel Case).
 */
packaging: ReleasePackaging, 
/**
 * Official status of the release (e.g. Official, Promotional, Remastered).
 */
status: ReleaseStatus, 
/**
 * Release date.
 */
date: Date, 
/**
 * Country where the release was published or made available.
 */
country: Country, };
