// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenreId } from "../shared/GenreId";
import type { Key } from "../shared/Key";
import type { PartyId } from "../shared/PartyId";
import type { RecordingVersion } from "./RecordingVersion";

/**
 * Represents a music recording.
 *
 * This structure contains all metadata related to a recorded performance,
 * including production details, performers, and technical specifications.
 *
 * # Examples
 *
 * ## Basic Recording
 *
 * ```rust
 * use allfeat_midds_v2::{
 *     recording::{Recording, RecordingVersion},
 *     shared::PartyId,
 *     shared::Key,
 *     shared::genres::GenreId
 * };
 *
 * let recording = Recording {
 *     isrc: b"USABC2312345".to_vec().try_into().unwrap(),
 *     musical_work: 12345,
 *     artist: PartyId::Ipi(123456789),
 *     producers: vec![].try_into().unwrap(),
 *     performers: vec![].try_into().unwrap(),
 *     contributors: vec![].try_into().unwrap(),
 *     title: b"My Recording".to_vec().try_into().unwrap(),
 *     title_aliases: vec![].try_into().unwrap(),
 *     recording_year: Some(2024),
 *     genres: vec![GenreId::Pop].try_into().unwrap(),
 *     version: Some(RecordingVersion::Original),
 *     duration: Some(180),
 *     bpm: Some(120),
 *     key: Some(Key::C),
 *     recording_place: None,
 *     mixing_place: None,
 *     mastering_place: None,
 * };
 * ```
 */
export type Recording = { 
/**
 * ISRC (International Standard Recording Code) that uniquely identifies this recording.
 */
isrc: string, 
/**
 * The linked musical work this recording is based on (must refer to a registered MIDDS).
 */
musicalWork: bigint, artist: PartyId, producers: Array<PartyId>, performers: Array<PartyId>, contributors: Array<PartyId>, 
/**
 * Main title of the recording.
 */
title: string, 
/**
 * Optional list of alternative titles for the recording.
 */
titleAliases: Array<string>, 
/**
 * Year the recording was made (4-digit Gregorian year).
 */
recordingYear?: number, 
/**
 * Music genres attributed to this recording.
 */
genres: Array<GenreId>, 
/**
 * Version or type of the recording (e.g., Remix, Acoustic, Live).
 */
version?: RecordingVersion, 
/**
 * Duration of the recording in seconds.
 */
duration?: number, 
/**
 * Beats per minute (BPM), representing the tempo of the recording.
 */
bpm?: number, 
/**
 * Musical key (e.g., C, G#, etc.) the recording is in.
 */
key?: Key, 
/**
 * Free-text field indicating where the recording took place.
 */
recordingPlace: string, 
/**
 * Free-text field indicating where the mixing of the recording occurred.
 */
mixingPlace: string, 
/**
 * Free-text field indicating where the mastering of the recording occurred.
 */
masteringPlace: string, };
