// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingVersion = "Original" | "Live" | "RadioEdit" | "TvTrack" | "Single" | "Remix" | "Cover" | "Acoustic" | "Acapella" | "Instrumental" | "Orchestral" | "Extended" | "AlternateTake" | "ReRecorded" | "Karaoke" | "Dance" | "Dub" | "Clean" | "Rehearsal" | "Demo" | "Edit";
