// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum representing all major and minor keys, including sharps, flats,
 * and their enharmonic equivalents.
 *
 * This can be used to specify the musical key of a track or composition
 * with precise notation.
 *
 * # Naming Convention
 *
 * - `m` suffix indicates minor keys
 * - `s` suffix indicates sharp (#)
 * - `b` suffix indicates flat (♭)
 * - Enharmonic equivalents are preserved for exact notation
 *
 * # Examples
 *
 * ```rust
 * use allfeat_midds_v2::shared::Key;
 *
 * let c_major = Key::C;
 * let a_minor = Key::Am;
 * let f_sharp_major = Key::Fs;
 * let g_flat_major = Key::Gb; // Enharmonic equivalent of F#
 * ```
 */
export type Key = "A" | "Am" | "As" | "Asm" | "Ab" | "Abm" | "B" | "Bm" | "Bs" | "Bsm" | "Bb" | "Bbm" | "C" | "Cm" | "Cs" | "Csm" | "Cb" | "Cbm" | "D" | "Dm" | "Ds" | "Dsm" | "Db" | "Dbm" | "E" | "Em" | "Es" | "Esm" | "Eb" | "Ebm" | "F" | "Fm" | "Fs" | "Fsm" | "Fb" | "Fbm" | "G" | "Gm" | "Gs" | "Gsm" | "Gb" | "Gbm";
