// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum representing the language in which MIDDS metadata is written.
 *
 * This is used to identify the language context of the metadata fields.
 * Supports major world languages used in the music industry.
 *
 * # Example
 *
 * ```rust
 * use allfeat_midds_v2::shared::Language;
 *
 * let song_language = Language::English;
 * let french_song = Language::French;
 * ```
 */
export type Language = "English" | "French" | "Spanish" | "German" | "Italian" | "Portuguese" | "Russian" | "Chinese" | "Japanese" | "Korean" | "Arabic" | "Hindi" | "Dutch" | "Swedish" | "Norwegian" | "Finnish" | "Polish" | "Turkish" | "Hebrew" | "Greek" | "Latin" | "Esperanto";
