// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClassicalInfo = { 
/**
 * Opus number assigned by the composer or music cataloger.
 *
 * Opus numbers are sequential numbers assigned to works, often by the composer,
 * to indicate order of composition or publication. Format examples:
 * - "Op. 27 No. 2" (Beethoven's Moonlight Sonata)
 * - "Op. 9" (simple opus number)
 * - "Op. posthumous" (published after death)
 */
opus?: string, 
/**
 * Catalog number from a scholarly music catalog.
 *
 * Professional musicologists create comprehensive catalogs of composers' works.
 * Examples include:
 * - "K. 551" (Mozart's Jupiter Symphony in Köchel catalog)
 * - "BWV 1006" (Bach work in Bach-Werke-Verzeichnis)
 * - "D. 944" (Schubert work in Deutsch catalog)
 * - "Hob. XVI:50" (Haydn work in Hoboken catalog)
 */
catalogNumber?: string, 
/**
 * Number of distinct vocal parts in the composition.
 *
 * For works with vocal components, this indicates how many separate
 * vocal lines exist:
 * - 1 = Solo voice
 * - 4 = SATB choir (Soprano, Alto, Tenor, Bass)
 * - 8 = Double choir
 * - None = Instrumental work with no vocal parts
 */
numberOfVoices?: number, };
