// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartyId } from "../shared/PartyId";
import type { CreatorRole } from "./CreatorRole";

/**
 * Represents a creator or contributor to a musical work.
 *
 * This structure links a party (identified by their industry IDs) to their
 * specific role in the creation of a musical work.
 *
 * # Example
 *
 * ```rust
 * use allfeat_midds_v2::{
 *     musical_work::{Creator, CreatorRole},
 *     shared::PartyId,
 * };
 *
 * let composer = Creator {
 *     id: PartyId::Ipi(123456789),
 *     role: CreatorRole::Composer,
 * };
 *
 * let lyricist = Creator {
 *     id: PartyId::Ipi(987654321),
 *     role: CreatorRole::Author,
 * };
 * ```
 */
export type Creator = { 
/**
 * Identifier of the person or entity involved in the work.
 */
id: PartyId, 
/**
 * The specific role this creator played in the creation of the work.
 */
role: CreatorRole, };
