// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Container for parties that have both IPI and ISNI identifiers.
 *
 * This struct is used within [`PartyId::Both`] to hold both identifier types
 * when a party is known by both systems.
 *
 * # Example
 *
 * ```rust
 * use allfeat_midds_v2::shared::BothIdsContainer;
 *
 * let container = BothIdsContainer {
 *     ipi: 123456789,
 *     isni: b"000000012345678X".to_vec().try_into().unwrap(),
 * };
 * ```
 */
export type BothIdsContainer = { 
/**
 * The IPI identifier for this party.
 */
ipi: bigint, 
/**
 * The ISNI identifier for this party.
 */
isni: string, };
