// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Representation of a date for use in MIDDS fields.
 *
 * This struct contains the year, month, and day in numerical format.
 * It is meant for simple, unambiguous date representation without timezone or time information.
 *
 * # Example
 *
 * ```rust
 * use allfeat_midds_v2::shared::Date;
 *
 * let release_date = Date {
 *     year: 2024,
 *     month: 6,
 *     day: 15,
 * };
 * ```
 */
export type Date = { year: number, month: number, day: number, };
